#!/usr/bin/python3
# -*- coding: utf-8 -*-

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#  Author: Karol Pałac (palac.karol@gmail.com)



"""
Sample language model (Spanish) for developers
Change model data and run the script to generate header file, and then copy it to language models dir

"""

import pickle 
import snowballstemmer





# Modify data in the dictionary below
model = {
# List of possible names (e.g. if given in feed's meta info. First name on this list is a model name, so they need to be unique
# First item on the list is used as a model name in SmallSem
'names' : ('es','ES','es-*','Es-*','ES-*', 'spa', 'SPA', 'spanish', 'Spanish', 'SPANISH', 'esp', 'esp-*', 'español', 'Español', ),

# Stemmer and pyphen modules
'stemmer' : 'spanish', #Must be in snowballstemmer language list or None for no stemming
'pyphen' : 'es',


# This data is useful for language detection
'alphabet' : 'abcdefghijklmnopqrstuvwxyzáéíóúüñ',
'numerals' : '1234567890',
'capitals' : 'ABCDEFGHIJKLMNOPRSTUVWXYZ', # This is useful to detect capitalized items but not essential
'vowels' : 'aeiouyáéíóúü',
'consonants' : 'bcdfghjklmnpqrstvwxzñ',
'unique_chars' : 'áéíóúüñ¿¡',
'charsets' : ('iso-8859-1', 'windows-1252',),

# Linguistic info
'writing_system' : 1, # 1 - alphabetic, 2 - logographic
'bicameral' : 1, # is language 'case-sensitive'?
'name_cap' : 1, # 1 - names capitalized, 2 - all nouns capitalized (e.g. German), 0 - no capitals (non-bicameral)

# Tokenizer
# It is advised to include patterns for emails, urls and other useful features for tokenisation
'REGEX_tokenizer' : r"""([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+|»|«|\w+['-'\w]\w+|\d+[\.,\d]+\d+|\.[a-z][0-9]+|[\.!\?¿¡'"”“””&,;:\[\]\{\}\(\)]|#[a-zA-Z0-9]*|\w+\d+|\d+\w+|\d+|\w+)""",

'sentence_chunker' : """(?:\.\.\.|\.|\?|!|¿|¡|^\s|[\n\t]*?)((?:\s+[A-Z]\w+|\"\s|\'\s|\n+).*?(?:\.\.\.|\.|\?|!|¿|¡| $))(?:\s+[A-Z]\w+|\"\s|\'\s|[\n\t]*?)""",

# Sentence beginnings and endings
'sent_beg' : ("\n","\t","\r","\r\n", '¿','¡','¿¿¿','¡¡¡','¿¿','¡¡',),
'sent_end' : ('.','...','!','?','!!!','!!','??','???'),

'divs' : ("\n","\t","\r","\r\n", '.','...','!','?','¿','¡','¿¿¿','¡¡¡','¿¿','¡¡','!!!','!!','??','???',',',':',';','[',']','(',')','{','}','"',"'",'“','>>>','>>','“','‘','”','<<<','<<','”','’',
          '<b>','<i>','<u>','</b>','</i>','</u>',),

# Punctation tokens
'punctation' : (',',':',';','[',']','(',')','{','}','','«','»','&'),

'par_beg' : ('(','[','{'),
'par_end' : (')',']','}'),


# Beginnings and endings of quotations
'quot_beg' : ('“','>>>','>>','“','‘'),
'quot_end' : ('”','<<<','<<','”','’'),
# Quotation marks without marked beginning/ending
'quot' : ("'",'"'),

# Emphasizers - from markup, style etc.
'emph_beg' : ('»',),
'emph_end' : ('«',),

# Stop words and swadesh list (latter used extensively for language detection and keyword extraction when Xapian DB is not present)
'stops' : ("a","actualmente","acuerdo","adelante","ademas","además","adrede","afirmó","agregó","ahi","ahora","ahí","al","algo","alguna","algunas","alguno","algunos","algún","alli","allí","alrededor","ambos","ampleamos","antano","antaño","ante","anterior","antes","apenas","aproximadamente","aquel","aquella","aquellas","aquello","aquellos","aqui","aquél","aquélla","aquéllas","aquéllos","aquí","arriba","arribaabajo","aseguró","asi","así","atras","aun","aunque","ayer","añadió","aún","b","bajo","bastante","bien","breve","buen","buena","buenas","bueno","buenos","c","cada","casi","cerca","cierta","ciertas","cierto","ciertos","cinco","claro","comentó","como","con","conmigo","conocer","conseguimos","conseguir","considera","consideró","consigo","consigue","consiguen","consigues","contigo","contra","cosas","creo","cual","cuales","cualquier","cuando","cuanta","cuantas","cuanto","cuantos","cuatro","cuenta","cuál","cuáles","cuándo","cuánta","cuántas","cuánto","cuántos","cómo","d","da","dado","dan","dar","de","debajo","debe","deben","debido","decir","dejó","del","delante","demasiado","demás","dentro","deprisa","desde","despacio","despues","después","detras","detrás","dia","dias","dice","dicen","dicho","dieron","diferente","diferentes","dijeron","dijo","dio","donde","dos","durante","día","días","dónde","e","ejemplo","el","ella","ellas","ello","ellos","embargo","empleais","emplean","emplear","empleas","empleo","en","encima","encuentra","enfrente","enseguida","entonces","entre","era","erais","eramos","eran","eras","eres","es","esa","esas","ese","eso","esos","esta","estaba","estabais","estaban","estabas","estad","estada","estadas","estado","estados","estais","estamos","estan","estando","estar","estaremos","estará","estarán","estarás","estaré","estaréis","estaría","estaríais","estaríamos","estarían","estarías","estas","este","estemos","esto","estos","estoy","estuve","estuviera","estuvierais","estuvieran","estuvieras","estuvieron","estuviese","estuvieseis","estuviesen","estuvieses","estuvimos","estuviste","estuvisteis","estuviéramos","estuviésemos","estuvo","está","estábamos","estáis","están","estás","esté","estéis","estén","estés","ex","excepto","existe","existen","explicó","expresó","f","fin","final","fue","fuera","fuerais","fueran","fueras","fueron","fuese","fueseis","fuesen","fueses","fui","fuimos","fuiste","fuisteis","fuéramos","fuésemos","g","general","gran","grandes","gueno","h","ha","haber","habia","habida","habidas","habido","habidos","habiendo","habla","hablan","habremos","habrá","habrán","habrás","habré","habréis","habría","habríais","habríamos","habrían","habrías","habéis","había","habíais","habíamos","habían","habías","hace","haceis","hacemos","hacen","hacer","hacerlo","haces","hacia","haciendo","hago","han","has","hasta","hay","haya","hayamos","hayan","hayas","hayáis","he","hecho","hemos","hicieron","hizo","horas","hoy","hube","hubiera","hubierais","hubieran","hubieras","hubieron","hubiese","hubieseis","hubiesen","hubieses","hubimos","hubiste","hubisteis","hubiéramos","hubiésemos","hubo","i","igual","incluso","indicó","informo","informó","intenta","intentais","intentamos","intentan","intentar","intentas","intento","ir","j","junto","k","l","la","lado","largo","las","le","lejos","les","llegó","lleva","llevar","lo","los","luego","lugar","m","mal","manera","manifestó","mas","mayor","me","mediante","medio","mejor","mencionó","menos","menudo","mi","mia","mias","mientras","mio","mios","mis","misma","mismas","mismo","mismos","modo","momento","mucha","muchas","mucho","muchos","muy","más","mí","mía","mías","mío","míos","n","nada","nadie","ni","ninguna","ningunas","ninguno","ningunos","ningún","no","nos","nosotras","nosotros","nuestra","nuestras","nuestro","nuestros","nueva","nuevas","nuevo","nuevos","nunca","o","ocho","os","otra","otras","otro","otros","p","pais","para","parece","parte","partir","pasada","pasado","paìs","peor","pero","pesar","poca","pocas","poco","pocos","podeis","podemos","poder","podria","podriais","podriamos","podrian","podrias","podrá","podrán","podría","podrían","poner","por","por qué","porque","posible","primer","primera","primero","primeros","principalmente","pronto","propia","propias","propio","propios","proximo","próximo","próximos","pudo","pueda","puede","pueden","puedo","pues","q","qeu","que","quedó","queremos","quien","quienes","quiere","quiza","quizas","quizá","quizás","quién","quiénes","qué","r","raras","realizado","realizar","realizó","repente","respecto","s","sabe","sabeis","sabemos","saben","saber","sabes","sal","salvo","se","sea","seamos","sean","seas","segun","segunda","segundo","según","seis","ser","sera","seremos","será","serán","serás","seré","seréis","sería","seríais","seríamos","serían","serías","seáis","señaló","si","sido","siempre","siendo","siete","sigue","siguiente","sin","sino","sobre","sois","sola","solamente","solas","solo","solos","somos","son","soy","soyos","su","supuesto","sus","suya","suyas","suyo","suyos","sé","sí","sólo","t","tal","tambien","también","tampoco","tan","tanto","tarde","te","temprano","tendremos","tendrá","tendrán","tendrás","tendré","tendréis","tendría","tendríais","tendríamos","tendrían","tendrías","tened","teneis","tenemos","tener","tenga","tengamos","tengan","tengas","tengo","tengáis","tenida","tenidas","tenido","tenidos","teniendo","tenéis","tenía","teníais","teníamos","tenían","tenías","tercera","ti","tiempo","tiene","tienen","tienes","toda","todas","todavia","todavía","todo","todos","total","trabaja","trabajais","trabajamos","trabajan","trabajar","trabajas","trabajo","tras","trata","través","tres","tu","tus","tuve","tuviera","tuvierais","tuvieran","tuvieras","tuvieron","tuviese","tuvieseis","tuviesen","tuvieses","tuvimos","tuviste","tuvisteis","tuviéramos","tuviésemos","tuvo","tuya","tuyas","tuyo","tuyos","tú","u","ultimo","un","una","unas","uno","unos","usa","usais","usamos","usan","usar","usas","uso","usted","ustedes","v","va","vais","valor","vamos","van","varias","varios","vaya","veces","ver","verdad","verdadera","verdadero","vez","vosotras","vosotros","voy","vuestra","vuestras","vuestro","vuestros","w","x","y","ya","yo","z","él","éramos","ésa","ésas","ése","ésos","ésta","éstas","éste","éstos","última","últimas","último","últimos"),

'swadesh' : (
'''yo''',
'''tú''', '''vos''', '''usted''',
'''él, ella''',
'''nosotros''', '''nosotras''',
'''vosotros''', '''vosotras''', '''ustedes''',
'''ellos''', '''ellas''',
'''este''',
'''ese''', '''aquel''',
'''aquí''', '''acá''',
'''ahí''',
'''quién''',
'''qué''',
'''dónde''',
'''cuándo''',
'''cómo''',
'''no''',
'''todo''',
'''mucho''',
'''alguno''',
'''poco''',
'''otro''',
'''uno''',
'''dos''',
'''tres''',
'''cuatro''',
'''cinco''',
'''grande''',
'''largo''',
'''ancho''',
'''grueso''',
'''pesado''',
'''pequeño''',
'''corto''',
'''estrecho''', '''angosto''',
'''delgado''', '''flaco''',
'''mujer''',
'''varón''',
'''hombre''',
'''niño''',
'''esposa''', '''mujer''',
'''esposo''', '''marido''',
'''madre''',
'''padre''',
'''animal''',
'''pez''', '''pescado''',
'''pájaro''',
'''perro''',
'''piojo''',
'''serpiente''', '''víbora''', '''culebra''',
'''gusano''',
'''árbol''',
'''bosque''',
'''palo''',
'''fruta''',
'''semilla''',
'''hoja''',
'''raíz''',
'''corteza''',
'''flor''',
'''hierba''', '''grama''',
'''cuerda''',
'''piel''',
'''carne''',
'''sangre''',
'''hueso''',
'''grasa''',
'''huevo''',
'''cuerno''',
'''cola''',
'''pluma''',
'''pelo''', '''cabello''',
'''cabeza''',
'''oreja''',
'''ojo''',
'''nariz''',
'''boca''',
'''diente''',
'''lengua''',
'''uña''',
'''pie''',
'''pierna''',
'''rodilla''',
'''mano''',
'''ala''',
'''barriga''', '''vientre''',
'''tripas''',
'''cuello''',
'''espalda''',
'''pecho''',
'''corazón''',
'''hígado''',
'''beber''',
'''comer''',
'''morder''',
'''chupar''',
'''escupir''',
'''vomitar''',
'''soplar''',
'''respirar''',
'''reír''',
'''ver''',
'''oír''',
'''saber''',
'''pensar''',
'''oler''',
'''temer''',
'''dormir''',
'''vivir''',
'''morir''',
'''matar''',
'''pelear''',
'''cazar''',
'''golpear''',
'''cortar''',
'''partir''',
'''apuñalar''',
'''arañar''', '''rascar''',
'''cavar''', '''excavar''',
'''nadar''',
'''volar''',
'''caminar''',
'''venir''',
'''echarse''', '''yacer''', '''estar''', '''en''', '''el''', '''suelo''',
'''sentarse''','''sentado''',
'''levantarse''', '''pie''',
'''girar''', '''dar''', '''una''', '''vuelta''',
'''caer''',
'''dar''',
'''tener''',
'''apretar''',
'''frotar''',
'''lavar''',
'''limpiar''',
'''tirar''', '''jalar''', '''halar''',
'''empujar''',
'''tirar''', '''arrojar''',
'''atar''',
'''coser''',
'''contar''',
'''decir''',
'''cantar''',
'''jugar''',
'''flotar''',
'''fluir''',
'''congelarse''', '''helar''',
'''hincharse''',
'''sol''',
'''luna''',
'''estrella''',
'''agua''',
'''lluvia''',
'''río''',
'''lago''',
'''mar''',
'''sal''',
'''piedra''',
'''arena''',
'''polvo''',
'''tierra''',
'''nube''',
'''niebla''',
'''cielo''',
'''viento''',
'''nieve''',
'''hielo''',
'''humo''',
'''fuego''',
'''cenizas''',
'''quemar''',
'''camino''',
'''montaña''',
'''rojo''',
'''verde''',
'''amarillo''',
'''blanco''',
'''negro''',
'''noche''',
'''día''',
'''año''',
'''caliente''', '''cálido''',
'''frío''',
'''lleno''',
'''nuevo''',
'''viejo''',
'''bueno''',
'''malo''',
'''podrido''',
'''sucio''',
'''recto''',
'''redondo''',
'''agudo''', '''afilado''',
'''sin''', '''filo''', '''desafilado''', '''embotado''', '''romo''',
'''liso''',
'''mojado''',
'''seco''',
'''correcto''',
'''cerca''',
'''lejos''',
'''derecha''',
'''izquierda''',
'''en''',
'''en''',
'''con''',
'''y''', '''e''',
'''si''',
'''porque''',
'''nombre''',
),

'copulas' : (),

# Normalize strange chars in tokens
'token_replacements' : {
'‘' : "'",
'’' : "'",
},


# Aliases will be expanded upon tokenization, case sensitive
'aliases' :          {},


# Morphology type and -fixes
'morphology' : 1,
'prefixes' : (),
'suffixes' : (),
'name_suffixes' : (),
'infixes' : (),




# List of common words for lookups (faster than dictionaries in most cases), easily found on the internet
'commons' : (
'''a''','''de''','''institución''','''presentación''',
'''a través de''','''debate''','''institucional''','''presentar''',
'''abril''','''deber''','''instituto''','''presente''',
'''abrir''','''década''','''instrumento''','''presidente''',
'''académico''','''decidir''','''integral''','''presupuesto''',
'''acceso''','''decir''','''integrar''','''pretender''',
'''acción''','''decisión''','''intentar''','''prever''',
'''aceptar''','''declaración''','''interés''','''previo''',
'''acercar''','''declarar''','''interesar''','''primero''',
'''acompañar''','''decreto''','''interior''','''principal''',
'''actividad''','''dedicar''','''internacional''','''principio''',
'''acto''','''defensa''','''internet''','''privar''',
'''actor''','''definir''','''interno''','''problema''',
'''actual''','''dejar''','''intervención''','''procedimiento''',
'''actualmente''','''delito''','''inversión''','''proceso''',
'''actuar''','''demanda''','''investigación''','''producción''',
'''acuerdo''','''demostrar''','''invitar''','''producir''',
'''adecuar''','''denominar''','''ir''','''producto''',
'''adelante''','''dentro''','''jefe''','''productor''',
'''además''','''departamento''','''jornada''','''profesional''',
'''administración''','''depender''','''joven''','''profesor''',
'''administrativo''','''deportivo''','''judicial''','''programa''',
'''adquirir''','''derecho''','''juego''','''promedio''',
'''advertir''','''desarrollar''','''juez''','''promover''',
'''afectar''','''desarrollo''','''jugador''','''propiedad''',
'''afirmar''','''desde''','''jugar''','''propio''',
'''agente''','''desear''','''juicio''','''proponer''',
'''agosto''','''después''','''julio''','''propuesta''',
'''agregar''','''destacar''','''junio''','''protección''',
'''agua''','''destinar''','''junto''','''proteger''',
'''ahí''','''detalle''','''jurídico''','''provincia''',
'''ahora''','''detener''','''justicia''','''provincial''',
'''aire''','''determinar''','''labor''','''provocar''',
'''alcanzar''','''día''','''laboral''','''próximo''',
'''algo''','''diario''','''lado''','''proyecto''',
'''alguien''','''diciembre''','''largo''','''prueba''',
'''alguno''','''diferencia''','''le''','''publicar''',
'''alimento''','''diferente''','''leer''','''público''',
'''allá''','''difícil''','''legal''','''pueblo''',
'''allí''','''digital''','''ley''','''puerta''',
'''alrededor''','''dinero''','''libertad''','''puerto''',
'''alto''','''dios''','''libre''','''pues''',
'''alumno''','''diputado''','''libro''','''puesto''',
'''ambiental''','''dirección''','''líder''','''punto''',
'''ambiente''','''directo''','''limitar''','''que''',
'''ámbito''','''director''','''línea''','''qué''',
'''ambos''','''dirigente''','''lista''','''quedar''',
'''América''','''dirigir''','''llamar''','''querer''',
'''amigo''','''diseño''','''llegar''','''quien''',
'''amor''','''disfrutar''','''llevar''','''quién''',
'''amplio''','''disponer''','''llevar a cabo''','''razón''',
'''análisis''','''disponible''','''lo''','''real''',
'''analizar''','''disposición''','''local''','''realidad''',
'''año''','''distinto''','''lograr''','''realizar''',
'''ante''','''distrito''','''lucha''','''recibir''',
'''anterior''','''diverso''','''luego''','''reconocer''',
'''antes''','''docente''','''lugar''','''reconocimiento''',
'''anunciar''','''documento''','''lunes''','''recordar''',
'''aparecer''','''dólar''','''luz''','''recuperar''',
'''aplicación''','''domingo''','''madre''','''recurso''',
'''aplicar''','''don''','''maestro''','''red''',
'''aportar''','''donde''','''malo''','''reducir''',
'''apoyar''','''duda''','''mañana''','''referencia''',
'''apoyo''','''durante''','''manejo''','''referir''',
'''aprender''','''economía''','''manera''','''reforma''',
'''aprobar''','''económico''','''manifestar''','''régimen''',
'''aprovechar''','''edad''','''mano''','''región''',
'''aquel''','''edición''','''mantener''','''regional''',
'''aquí''','''edificio''','''mar''','''registrar''',
'''área''','''educación''','''marca''','''registro''',
'''Argentina''','''educativo''','''marcar''','''relación''',
'''argentino''','''efecto''','''marco''','''relacionar''',
'''armar''','''efectuar''','''marzo''','''representante''',
'''arte''','''ejemplo''','''mas''','''representar''',
'''artículo''','''ejercicio''','''más''','''república''',
'''artista''','''el''','''materia''','''requerir''',
'''asegurar''','''él''','''material''','''requisito''',
'''así''','''elaborar''','''máximo''','''resolución''',
'''asimismo''','''elección''','''mayo''','''resolver''',
'''asistir''','''electoral''','''mayor''','''respectivo''',
'''asociación''','''eléctrico''','''mayoría''','''respecto''',
'''asociar''','''electrónico''','''me''','''responder''',
'''aspecto''','''elegir''','''mediante''','''responsabilidad''',
'''asumir''','''elemento''','''médico''','''responsable''',
'''asunto''','''ello''','''medida''','''respuesta''',
'''atención''','''ellos''','''medio''','''resto''',
'''atender''','''emitir''','''mejor''','''resultado''',
'''aumentar''','''empezar''','''mejorar''','''resultar''',
'''aumento''','''empleo''','''mencionar''','''reunión''',
'''aun''','''empresa''','''menor''','''reunir''',
'''aunque''','''en''','''menos''','''revista''',
'''auto''','''encontrar''','''mensaje''','''riesgo''',
'''autor''','''encuentro''','''mercado''','''río''',
'''autoridad''','''energía''','''mes''','''rojo''',
'''avanzar''','''enero''','''mesa''','''rural''',
'''ayer''','''enfermedad''','''método''','''ruta''',
'''ayuda''','''enfrentar''','''metro''','''sábado''',
'''ayudar''','''entender''','''mexicano''','''saber''',
'''bajar''','''entidad''','''México''','''sacar''',
'''bajo''','''entonces''','''mi''','''sala''',
'''banco''','''entrada''','''miembro''','''salida''',
'''banda''','''entrar''','''mientras''','''salir''',
'''barrio''','''entre''','''militar''','''salud''',
'''basar''','''entrega''','''mínimo''','''san''',
'''base''','''entregar''','''ministerio''','''Santiago de Chile''',
'''básico''','''enviar''','''ministro''','''santo''',
'''beneficio''','''época''','''minuto''','''se''',
'''bien''','''equipo''','''mirar''','''secretario''',
'''blanco''','''error''','''mismo''','''sector''',
'''brindar''','''escenario''','''modelo''','''sede''',
'''bueno''','''escribir''','''modificar''','''seguir''',
'''Buenos Aires''','''escuchar''','''modo''','''según''',
'''buscar''','''escuela''','''momento''','''segundo''',
'''cabeza''','''ese''','''morir''','''seguridad''',
'''cada''','''esfuerzo''','''mostrar''','''seguro''',
'''caer''','''espacio''','''motivo''','''selección''',
'''calidad''','''España''','''motor''','''semana''',
'''calle''','''español''','''movimiento''','''señalar''',
'''cámara''','''especial''','''mucho''','''señor''',
'''cambiar''','''especialmente''','''muerte''','''sentar''',
'''cambio''','''especie''','''muestra''','''sentencia''',
'''camino''','''específico''','''mujer''','''sentido''',
'''campaña''','''esperar''','''mundial''','''sentir''',
'''campo''','''establecer''','''mundo''','''septiembre''',
'''candidato''','''estado''','''municipal''','''ser''',
'''cantidad''','''Estados Unidos''','''municipio''','''serie''',
'''capacidad''','''estar''','''música''','''servicio''',
'''capital''','''estatal''','''muy''','''servir''',
'''carácter''','''este''','''nacer''','''si''',
'''característica''','''estilo''','''nación''','''sí''',
'''carga''','''estimar''','''nacional''','''siempre''',
'''cargo''','''estrategia''','''nada''','''siglo''',
'''carrera''','''estructura''','''nadie''','''significar''',
'''carta''','''estudiante''','''natural''','''siguiente''',
'''casa''','''estudiar''','''naturaleza''','''similar''',
'''casi''','''estudio''','''necesario''','''sin''',
'''caso''','''etapa''','''necesidad''','''sin embargo''',
'''categoría''','''etcétera''','''necesitar''','''sino''',
'''causa''','''evaluación''','''negocio''','''sistema''',
'''causar''','''evaluar''','''negro''','''sitio''',
'''celebrar''','''evento''','''ni''','''situación''',
'''central''','''evitar''','''ninguno''','''sobre''',
'''centro''','''ex''','''niño''','''social''',
'''cerca''','''excelente''','''nivel''','''sociedad''',
'''cerrar''','''exigir''','''no''','''solicitar''',
'''chico''','''existir''','''noche''','''solicitud''',
'''Chile''','''éxito''','''nombre''','''solo''',
'''ciencia''','''experiencia''','''norma''','''sólo''',
'''científico''','''explicar''','''norte''','''solución''',
'''cierto''','''exponer''','''nos''','''sostener''',
'''citar''','''expresar''','''nosotros''','''su''',
'''ciudad''','''factor''','''nota''','''subir''',
'''ciudadano''','''facultad''','''noviembre''','''suceder''',
'''civil''','''falta''','''nuestro''','''sufrir''',
'''claro''','''faltar''','''nuevo''','''sujeto''',
'''clase''','''familia''','''número''','''sumar''',
'''cliente''','''familiar''','''nunca''','''superar''',
'''club''','''favor''','''o''','''superior''',
'''código''','''fe''','''objetivo''','''suponer''',
'''colegio''','''febrero''','''objeto''','''sur''',
'''colocar''','''fecha''','''obligación''','''surgir''',
'''Colombia''','''federal''','''obligar''','''tal''',
'''color''','''fiesta''','''obra''','''taller''',
'''comentar''','''figura''','''observar''','''también''',
'''comentario''','''fin''','''obtener''','''tampoco''',
'''comenzar''','''final''','''ocasión''','''tanto''',
'''comercial''','''finalmente''','''octubre''','''tarde''',
'''comercio''','''financiero''','''ocupar''','''tarea''',
'''comisión''','''firma''','''ocurrir''','''te''',
'''como''','''firmar''','''oferta''','''técnica''',
'''cómo''','''fiscal''','''oficial''','''técnico''',
'''compañero''','''físico''','''oficina''','''tecnología''',
'''compañía''','''fondo''','''ofrecer''','''tecnológico''',
'''compartir''','''forma''','''opción''','''tema''',
'''competencia''','''formación''','''operación''','''tener''',
'''completo''','''formar''','''opinión''','''tercero''',
'''compra''','''foto''','''oportunidad''','''terminar''',
'''comprar''','''frente a''','''orden''','''término''',
'''comprender''','''fuente''','''ordenar''','''terreno''',
'''compromiso''','''fuera''','''organismo''','''territorio''',
'''común''','''fuerte''','''organización''','''texto''',
'''comunicación''','''fuerza''','''organizar''','''tiempo''',
'''comunidad''','''función''','''origen''','''tierra''',
'''con''','''funcionar''','''original''','''tipo''',
'''concepto''','''funcionario''','''otorgar''','''titular''',
'''concluir''','''fundamental''','''otro''','''título''',
'''condición''','''futuro''','''paciente''','''tocar''',
'''confirmar''','''ganar''','''padre''','''todavía''',
'''conflicto''','''garantizar''','''pagar''','''todo''',
'''conformar''','''gasto''','''página''','''tomar''',
'''congreso''','''generación''','''pago''','''total''',
'''conjunto''','''general''','''país''','''trabajador''',
'''conocer''','''generar''','''palabra''','''trabajar''',
'''conocimiento''','''género''','''papel''','''trabajo''',
'''consecuencia''','''gente''','''para''','''tradicional''',
'''conseguir''','''gestión''','''parecer''','''traer''',
'''consejo''','''gobernador''','''parque''','''transporte''',
'''considerar''','''gobierno''','''parte''','''tras''',
'''constitución''','''gracia''','''participación''','''tratamiento''',
'''constitucional''','''grado''','''participar''','''tratar''',
'''constituir''','''grande''','''particular''','''tribunal''',
'''construcción''','''grupo''','''partido''','''tu''',
'''construir''','''guerra''','''partir''','''ubicar''',
'''consulta''','''gustar''','''pasar''','''último''',
'''consumo''','''haber''','''paso''','''único''',
'''contacto''','''hablar''','''paz''','''unidad''',
'''contar''','''hacer''','''pedir''','''unión''',
'''contener''','''hacia''','''película''','''unir''',
'''contenido''','''hasta''','''penal''','''universidad''',
'''contexto''','''hecho''','''pensar''','''universitario''',
'''continuar''','''hermano''','''pequeño''','''uno''',
'''contra''','''herramienta''','''perder''','''urbano''',
'''contrato''','''hijo''','''período''','''usar''',
'''control''','''historia''','''permanente''','''uso''',
'''controlar''','''histórico''','''permitir''','''usted''',
'''convertir''','''hola''','''pero''','''usuario''',
'''correr''','''hombre''','''persona''','''utilizar''',
'''corresponder''','''hora''','''personal''','''valor''',
'''correspondiente''','''hospital''','''pesar''','''varios''',
'''corte''','''hotel''','''peso''','''vecino''',
'''cosa''','''hoy''','''piedra''','''vehículo''',
'''costa''','''humano''','''plan''','''vender''',
'''costo''','''idea''','''planta''','''venir''',
'''creación''','''identificar''','''plantear''','''venta''',
'''crear''','''igual''','''plata''','''ver''',
'''crecer''','''imagen''','''plaza''','''verdad''',
'''crecimiento''','''impacto''','''plazo''','''verdadero''',
'''crédito''','''implicar''','''población''','''versión''',
'''creer''','''imponer''','''poco''','''vez''',
'''crisis''','''importancia''','''poder''','''vía''',
'''criterio''','''importante''','''policía''','''viaje''',
'''cual''','''impuesto''','''política''','''víctima''',
'''cuál''','''incluir''','''político''','''victoria''',
'''cualquiera''','''incluso''','''poner''','''vida''',
'''cuando''','''incorporar''','''popular''','''video''',
'''cuanto''','''independiente''','''por''','''viernes''',
'''Cuba''','''indicar''','''porque''','''vincular''',
'''cubrir''','''industria''','''poseer''','''violencia''',
'''cuenta''','''industrial''','''posibilidad''','''visita''',
'''cuerpo''','''información''','''posible''','''visitar''',
'''cuestión''','''informar''','''posición''','''vista''',
'''cultura''','''informe''','''positivo''','''vivienda''',
'''cultural''','''ingresar''','''práctica''','''vivir''',
'''cumplimiento''','''ingreso''','''precio''','''volver''',
'''cumplir''','''iniciar''','''pregunta''','''voto''',
'''curso''','''iniciativa''','''preguntar''','''voz''',
'''cuyo''','''inicio''','''premio''','''y''',
'''daño''','''instalación''','''prensa''','''ya''',
'''dar''','''instalar''','''preparar''','''yo''',
'''dato''','''instancia''','''presencia''','''zona''',

)

}


# Stem commons
if model.get('stemmer') != None:
    stemmer = snowballstemmer.stemmer(model.get('stemmer','english'))
    commons_stemmed = []
    for w in model.get('commons',''):
        w = stemmer.stemWord(w)
        commons_stemmed.append(w)
    model['commons_stemmed'] = tuple(commons_stemmed)

# Generate pickle file
filename = model['names'][0] + '_model.pkl'

with open(filename, "wb") as write_file:
    pickle.dump(model, write_file)

